<script setup lang="ts">
import { computed,onMounted,ref } from 'vue';import { apiRequest } from '@/api/client';import { can } from '@/api/auth'
interface U{UserID:number;UserNO:string;UserName:string;DepartmentID:number|null;DepartmentName:string|null;Sex:string;ProfessionalTitle:string;Position:string;WageGrade:string;Status:number;HireDate:string;HrNumber:string}interface D{ID:number;DepartmentName:string}interface P{ModuleKey:string;CanView:boolean;CanEdit:boolean}
const users=ref<U[]>([]),departments=ref<D[]>([]),search=ref(''),editing=ref<Partial<U>|null>(null),permissions=ref<P[]|null>(null),permissionUser=ref<U|null>(null)
const informationInput=ref<HTMLInputElement|null>(null),fingerprintInput=ref<HTMLInputElement|null>(null),importing=ref(false),importMessage=ref(''),importErrors=ref<string[]>([])
const filtered=computed(()=>users.value.filter(u=>`${u.UserNO}${u.UserName}${u.DepartmentName}`.includes(search.value)))
const load=async()=>{users.value=(await apiRequest<{data:U[]}>('/api/admin/users')).data;departments.value=(await apiRequest<{data:D[]}>('/api/admin/departments')).data}
const open=(u?:U)=>editing.value=u?{...u}:{UserNO:'',UserName:'',DepartmentID:null,Status:1,HireDate:'1900-01-01'}
const save=async()=>{const b=editing.value!;await apiRequest(b.UserID?`/api/admin/users/${b.UserID}`:'/api/admin/users',{method:b.UserID?'PUT':'POST',body:JSON.stringify(b)});editing.value=null;await load()}
const reset=async(u:U)=>{if(confirm(`重置 ${u.UserName} 的密码为 Aa123456？`))await apiRequest(`/api/admin/users/${u.UserID}/reset-password`,{method:'POST'})}
const openPermissions=async(u:U)=>{permissionUser.value=u;permissions.value=(await apiRequest<{data:P[]}>(`/api/admin/users/${u.UserID}/permissions`)).data}
const savePermissions=async()=>{await apiRequest(`/api/admin/users/${permissionUser.value!.UserID}/permissions`,{method:'PUT',body:JSON.stringify({permissions:permissions.value})});permissions.value=null}
const moduleName=(k:string)=>({'dashboard':'工作台','machines':'机台管理','machine-types':'设备类型','collection':'采集配置','attendance':'考勤打卡','reports':'报表中心','users':'用户管理','departments':'部门管理','settings':'系统设置'} as Record<string,string>)[k]??k
const text=(value:unknown)=>String(value??'').trim()
const excelDate=(value:unknown)=>{if(value instanceof Date)return value.toISOString().slice(0,10);if(typeof value==='number'){const date=new Date(Date.UTC(1899,11,30)+value*86400000);return date.toISOString().slice(0,10)}const raw=text(value);if(!raw)return'1900-01-01';const date=new Date(raw);return Number.isNaN(date.getTime())?raw:date.toISOString().slice(0,10)}
const readSheet=async(file:File)=>{const{default:ExcelJS}=await import('exceljs');const workbook=new ExcelJS.Workbook();await workbook.xlsx.load(await file.arrayBuffer());const sheet=workbook.worksheets[0];if(!sheet)throw new Error('Excel 中没有工作表');const headers=new Map<string,number>();sheet.getRow(1).eachCell((cell,column)=>headers.set(text(cell.value),column));return{sheet,headers}}
const cell=(row:any,headers:Map<string,number>,names:string[])=>{for(const name of names){const column=headers.get(name);if(column)return row.getCell(column).value}return''}
const importInformation=async(event:Event)=>{const input=event.target as HTMLInputElement,file=input.files?.[0];input.value='';if(!file)return;importing.value=true;importMessage.value='';importErrors.value=[];try{const{sheet,headers}=await readSheet(file);const rows:any[]=[];sheet.eachRow((row,index)=>{if(index===1)return;const UserNO=text(cell(row,headers,['工号','用户工号','UserNO']));if(!UserNO)return;rows.push({UserNO,UserName:text(cell(row,headers,['姓名','用户姓名','UserName'])),DepartmentName:text(cell(row,headers,['部门','部门名称','DepartmentName'])),Sex:text(cell(row,headers,['性别','Sex'])),ProfessionalTitle:text(cell(row,headers,['职称','ProfessionalTitle'])),Position:text(cell(row,headers,['职务','职位','Position'])),WageGrade:text(cell(row,headers,['资位','工资等级','WageGrade'])),Status:['0','离职','停用'].includes(text(cell(row,headers,['状态','在职状态','Status'])))?0:1,HireDate:excelDate(cell(row,headers,['聘用日期','入职日期','HireDate'])),HrNumber:text(cell(row,headers,['指纹号','HR编号','HrNumber']))})});if(!rows.length)throw new Error('没有读取到用户；请确认首行包含“工号”和“姓名”');const result=await apiRequest<{data:{total:number;inserted:number;updated:number}}>('/api/admin/users/import-information',{method:'POST',body:JSON.stringify({rows})});importMessage.value=`用户信息导入完成：新增 ${result.data.inserted}，更新 ${result.data.updated}，共 ${result.data.total} 条`;await load()}catch(error){importErrors.value=[error instanceof Error?error.message:'用户信息导入失败']}finally{importing.value=false}}
const importFingerprints=async(event:Event)=>{const input=event.target as HTMLInputElement,file=input.files?.[0];input.value='';if(!file)return;importing.value=true;importMessage.value='';importErrors.value=[];try{const{sheet,headers}=await readSheet(file);const rows:any[]=[];sheet.eachRow((row,index)=>{if(index===1)return;const UserNO=text(cell(row,headers,['工号','用户工号','UserNO'])),HrNumber=text(cell(row,headers,['指纹号','HR编号','HrNumber']));if(UserNO||HrNumber)rows.push({UserNO,HrNumber})});if(!rows.length)throw new Error('没有读取到数据；请确认首行包含“工号”和“指纹号”');const result=await apiRequest<{data:{total:number;updated:number;errors:Array<{row:number;UserNO:string;message:string}>}}>('/api/admin/users/import-fingerprints',{method:'POST',body:JSON.stringify({rows})});importMessage.value=`指纹号导入完成：更新 ${result.data.updated}，共 ${result.data.total} 条`;importErrors.value=result.data.errors.map(item=>`第 ${item.row} 行（${item.UserNO}）：${item.message}`);await load()}catch(error){importErrors.value=[error instanceof Error?error.message:'指纹号导入失败']}finally{importing.value=false}}
const downloadTemplate=async(type:'information'|'fingerprint')=>{const{default:ExcelJS}=await import('exceljs');const workbook=new ExcelJS.Workbook(),sheet=workbook.addWorksheet(type==='information'?'用户信息':'用户指纹号');sheet.addRow(type==='information'?['工号','姓名','部门','性别','职称','职务','资位','状态','聘用日期','指纹号']:['工号','指纹号']);sheet.addRow(type==='information'?['XH001','示例用户','生产部','男','','','',1,'2026-01-01','10001']:['XH001','10001']);sheet.getRow(1).font={bold:true};sheet.columns.forEach(column=>column.width=16);const buffer=await workbook.xlsx.writeBuffer(),url=URL.createObjectURL(new Blob([new Uint8Array(buffer)])),link=document.createElement('a');link.href=url;link.download=type==='information'?'用户信息导入模板.xlsx':'用户指纹号导入模板.xlsx';link.click();URL.revokeObjectURL(url)}
onMounted(load)
</script>
<template><div class="card machine-card"><div class="resource-header"><div><span class="eyebrow">ACCOUNTS</span><h2>用户与权限</h2></div><div class="inline-actions"><input v-model="search" class="filter-input" placeholder="搜索工号、姓名或部门"><template v-if="can('users',true)"><button class="button button--ghost" :disabled="importing" @click="informationInput?.click()">导入用户信息</button><button class="button button--ghost" :disabled="importing" @click="fingerprintInput?.click()">导入指纹号</button><button class="button button--primary" @click="open()">新增用户</button><input ref="informationInput" hidden type="file" accept=".xlsx" @change="importInformation"><input ref="fingerprintInput" hidden type="file" accept=".xlsx" @change="importFingerprints"></template></div></div><div v-if="importing" class="notice">正在读取并导入 Excel…</div><div v-if="importMessage" class="notice">{{importMessage}}</div><div v-if="importErrors.length" class="notice notice--error"><strong>导入提示</strong><div v-for="message in importErrors.slice(0,20)" :key="message">{{message}}</div></div><div v-if="can('users',true)" class="import-help">Excel 首行使用模板列名；按工号新增或更新用户。<button class="text-button" @click="downloadTemplate('information')">下载用户信息模板</button><button class="text-button" @click="downloadTemplate('fingerprint')">下载指纹号模板</button></div><div class="table-wrap"><table><thead><tr><th>工号 / 姓名</th><th>部门</th><th>性别</th><th>职称 / 职务</th><th>指纹号</th><th>聘用日期</th><th>状态</th><th>操作</th></tr></thead><tbody><tr v-for="u in filtered" :key="u.UserID"><td><strong>{{u.UserNO}}</strong><span class="cell-subtitle">{{u.UserName}}</span></td><td>{{u.DepartmentName||'-'}}</td><td>{{u.Sex||'-'}}</td><td>{{u.ProfessionalTitle||'-'}}<span class="cell-subtitle">{{u.Position||'-'}}</span></td><td>{{u.HrNumber||'-'}}</td><td>{{u.HireDate}}</td><td><span :class="['status-pill',u.Status?'status-pill--on':'status-pill--off']">{{u.Status?'在职':'离职'}}</span></td><td><button v-if="can('users',true)" class="text-button" @click="open(u)">编辑</button><button v-if="can('users',true)" class="text-button" @click="openPermissions(u)">权限</button><button v-if="can('users',true)" class="text-button" @click="reset(u)">重置密码</button></td></tr></tbody></table></div></div>
<div v-if="editing" class="dialog-layer"><button class="dialog-scrim" @click="editing=null"/><form class="machine-dialog" @submit.prevent="save"><header class="machine-dialog__header"><h2>{{editing.UserID?'编辑用户':'新增用户'}}</h2><button type="button" class="icon-button" @click="editing=null">×</button></header><div class="machine-form"><div class="form-section form-grid"><label>工号<input v-model="editing.UserNO" required></label><label>姓名<input v-model="editing.UserName" required></label><label>部门<select v-model="editing.DepartmentID"><option :value="null">未分配</option><option v-for="d in departments" :value="d.ID">{{d.DepartmentName}}</option></select></label><label>性别<input v-model="editing.Sex"></label><label>职称<input v-model="editing.ProfessionalTitle"></label><label>职务<input v-model="editing.Position"></label><label>资位<input v-model="editing.WageGrade"></label><label>状态<select v-model.number="editing.Status"><option :value="1">在职</option><option :value="0">离职</option></select></label><label>聘用日期<input v-model="editing.HireDate" type="date" required></label><label>指纹号<input v-model="editing.HrNumber"></label></div><footer class="machine-dialog__footer"><button type="button" class="button button--ghost" @click="editing=null">取消</button><button class="button button--primary">保存</button></footer></div></form></div>
<div v-if="permissions" class="dialog-layer"><button class="dialog-scrim" @click="permissions=null"/><div class="permission-dialog"><h2>{{permissionUser?.UserName}} 的模块权限</h2><div v-for="p in permissions" class="permission-row"><strong>{{moduleName(p.ModuleKey)}}</strong><label><input v-model="p.CanView" type="checkbox"> 查看</label><label><input v-model="p.CanEdit" type="checkbox" @change="p.CanView ||= p.CanEdit"> 编辑</label></div><footer><button class="button button--ghost" @click="permissions=null">取消</button><button class="button button--primary" @click="savePermissions">保存权限</button></footer></div></div></template>
<style scoped>.import-help{padding:10px 24px;color:#637b96;font-size:12px}.import-help .text-button{margin-left:12px}</style>
